<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<html class="no-js">
    <!-- Start Head -->
    <head>
        <?php
            echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')
                                  ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1');
                                  
        ?>
        <!-- Meta Tag -->
        <?php $children = $this->viewModel()->getCurrent()->getChildren(); ?>  
        <title><?php echo $title = $this->escapeHtml(isset($children[0]->title) ? $children[0]->title : 'Evatix'); ?></title>
        
        <?php
        echo $this->headMeta()->appendName('author', 'Evatix')->appendName('application-name', 'Evatix template')
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendName('description', 'Evatix template - Responsive admin template. This template is designed to help you build the site administration without losing valuable time. Template contains all the important functions which must have one backend system. Build on great twitter boostrap framework.')
                ->appendName('keywords', 'admin, admin template, admin theme, responsive, responsive admin, responsive admin template, responsive theme, administration, administration template, administration theme, mobile, touch , responsive layout, boostrap, twitter boostrap');
        ?>
        
        <!-- styles -->
        <?php 
        
        echo $this->headLink()->appendStylesheet($this->basePath('assets/css/bootstrap/bootstrap.css'))
                        ->appendStylesheet($this->basePath('assets/css/bootstrap/bootstrap-responsive.css'))
                        ->appendStylesheet($this->basePath('assets/css/supr-theme/jquery.ui.supr.css')) 
                        ->appendStylesheet($this->basePath('assets/css/icons.css'))
                        ->appendStylesheet($this->basePath('assets/plugins/uniform/uniform.default.css'))
                        ->appendStylesheet($this->basePath('assets/css/main.css'))
                        ->appendStylesheet($this->basePath('assets/css/layout.css'))
                        ->appendStylesheet($this->basePath('assets/css/media.css'));
        ?>
        
        <script src="<?php echo $this->basePath('assets/js/modernizr-2.6.2-respond-1.1.0.min.js'); ?>"></script>
        
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="<?php echo $this->basePath('assets/js/html5.js'); ?>"></script>
        <![endif]-->
        <link rel="shortcut icon" href="<?php echo $this->basePath('assets/favicon.ico'); ?>" />
        <link rel="shortcut icon" href="<?php echo $this->basePath('assets/favicon.ico'); ?>" />
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->basePath('assets/apple-touch-icon-144-precomposed.png'); ?>" />
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->basePath('assets/apple-touch-icon-114-precomposed.png'); ?>" />
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->basePath('assets/apple-touch-icon-72-precomposed.png'); ?>" />
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->basePath('assets/apple-touch-icon-57-precomposed.png'); ?>" />
        
        <script type="text/javascript">
            //adding load class to body and hide page
            document.documentElement.className += 'loadstate';
        </script>

        <!-- Le javascript
        ================================================== -->
        <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/js/bootstrap/bootstrap.js'); ?>"></script>  
        <script type="text/javascript" src="<?php echo $this->basePath('assets/plugins/touch-punch/jquery.ui.touch-punch.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/plugins/ios-fix/ios-orientationchange-fix.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/plugins/validate/jquery.validate.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/plugins/uniform/jquery.uniform.min.js'); ?>"></script>
                
    </head>
    
    <!-- End Head -->
    
    
    <body class="loginPage">
        <!-- loading animation -->
        <div id="qLoverlay"></div>
        <div id="qLbar"></div>
        <div class="container-fluid">

            <div id="header">
    
                <div class="row-fluid">
    
                    <div class="navbar">
                        <div class="navbar-inner">
                          <div class="container">
                                <a class="brand" href="<?php echo $this->basePath(); ?>">
                                    <img src="<?php echo $this->basePath('assets/images/evatix_logo.png'); ?>" alt="Evatix Innovative Software" title="Evatix Innovative Software" />
                                </a>
                          </div>
                        </div><!-- /navbar-inner -->
                      </div><!-- /navbar -->
                    
    
                </div><!-- End .row-fluid -->
    
            </div><!-- End #header -->

        </div><!-- End .container-fluid -->  
        
        <!-- Global Mesage Show -->
        
        <?php 
        $ourView  = $children[0];
        if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : 
        ?>
            <ul class="flashMessages">
            <?php foreach ($ourView->flashMessages as $messages): ?>
                <?php foreach ($messages as $key => $message) : ?>
                    <li class="<?php echo $key; ?>"><?php echo $message; ?></li>
                <?php endforeach; ?>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        
        <!-- End Global Mesage Show -->
        
        <!-- Main Container -->
        <?php echo $this->content; ?>
        <!-- End Main Container -->
     
        
    </body>
</html>
