<?php $url = $this->getSettings('website_url'); ?>
<script type="text/javascript" src="<?php echo $url.$this->basePath('assets/plugins/validate/jquery.validate.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $url.$this->basePath('assets/design/frontend/default/js/password.strength.js'); ?>"></script>
<script type="text/javascript">
//<!--
    $(document).ready(function() {
    	
		$("#password").bind("keyup", checkVal);
    	
        $("#create_account").validate({
        	
            rules: {
            	
                email: {
                    required: true,
                    email: true
                },
                
				username: {
                    required: true
                },
                
				password: {
                    required: true,
                    minlength: 6,
                    maxlength: 255 
                }
				   
            },
            
            messages: {
            	
                email: {
                    required: "Email address is required",
                    email: 'Invalid email address'
                },
                
                username: {
                    required: "Username is required"
                },
                
                password: {
                    required: "Password is required",
                    maxlength: "Password should be at least 6-7 digit to be secure",
                    minlength: "Password should be at least 6-7 digit to be secure"
                }
                
            }   
            
        });
        
    });
    //-->
</script>

<div class="about_us">
	<div class="content" style="margin-top: 75px;">
		<p>Welcome to <span>JAKATOO,</span><br />
		the new business tool for you to generate more income<br/>Experience the new way of selling your products worldwide!<br/>Sign up now for free! No hidden cost!</p>
		
		<div class="step_account backgroundblue">
		
			<div class="fleft video ">
				<img src="<?php echo $url.$this->basePath('assets/design/frontend/default/images/video.png'); ?>" />
				<!--iframe width="100%" height="315" src="//www.youtube.com/embed/_MVne-ru1xY?feature=player_detailpage" frameborder="0" allowfullscreen></iframe -->
			</div>
			
			<div class="fright steps">
				<div class="steps_content">
				
		            <form class="submitForm" action="" method="post" id="create_account">
		            
			              <img class="step_image" src="<?php echo $url.$this->basePath('assets/design/frontend/default/images/steps.png'); ?>" alt="Jakato" />
			              <div style="width: 72%;margin: 20px auto;">
				              <input type="text" name="email" id="email" value="<?php echo isset($this->data['email']) ? $this->data['email'] : ''; ?>" placeholder="your email" /><br />
				              <input type="text" name="username" value="<?php echo isset($this->data['username']) ? $this->data['username'] : ''; ?>" id="username" placeholder="your username" /><br />
				              <input type="password" name="password" id="password" placeholder="your password"  /><br />
						  </div>
						  
			              <input type="image" src="<?php echo $url.$this->basePath('assets/design/frontend/default/images/start_button.png'); ?>" style="width: 120px;height: auto;" />
			              
		           	</form>
		           	
				</div>
			</div>
			
		</div>
	</div>
</div>
