<?php 
if ($this->isajax): 
	header("Content-type: text/xml");

	// Start XML file, create parent node
	$dom = new DOMDocument("1.0");
	$node = $dom->createElement("markers");
	$parnode = $dom->appendChild($node);
	foreach ($this->userLst as $user) {
		$node = $dom->createElement("marker");
		$newnode = $parnode->appendChild($node);
		$newnode->setAttribute("name", $user['name']);
		$newnode->setAttribute("address", $user['formatted_address']);
		$newnode->setAttribute("lat", $user['lat']);
		$newnode->setAttribute("lng", $user['lng']);
		$newnode->setAttribute("distance", $user['distance']);
	}
	echo $dom->saveXML();
	exit;
else: ?>
	<?php $url = $this->getSettings('website_url'); ?>
	<script src="https://maps.googleapis.com/maps/api/js" type="text/javascript"></script>
	<script type="text/javascript">
	    //<![CDATA[
	    var map;
	    var markers = [];
	    var infoWindow;
	    var locationSelect;
	
	    function load() {
	      map = new google.maps.Map(document.getElementById("map"), {
	        center: new google.maps.LatLng(40, -100),
	        zoom: 4,
	        mapTypeId: 'roadmap',
	        mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU}
	      });
	      infoWindow = new google.maps.InfoWindow();
	
	      locationSelect = document.getElementById("locationSelect");
	      locationSelect.onchange = function() {
	        var markerNum = locationSelect.options[locationSelect.selectedIndex].value;
	        if (markerNum != "none"){
	          google.maps.event.trigger(markers[markerNum], 'click');
	        }
	      };
	   }
	
	   function searchLocations() {
	     var address = document.getElementById("addressInput").value;
	     var geocoder = new google.maps.Geocoder();
	     geocoder.geocode({address: address}, function(results, status) {
	       if (status == google.maps.GeocoderStatus.OK) {
	        searchLocationsNear(results[0].geometry.location);
	       } else {
	         alert(address + ' not found');
	       }
	     });
	   }
	
	   function clearLocations() {
	     infoWindow.close();
	     for (var i = 0; i < markers.length; i++) {
	       markers[i].setMap(null);
	     }
	     markers.length = 0;
	
	     locationSelect.innerHTML = "";
	     var option = document.createElement("option");
	     option.value = "none";
	     option.innerHTML = "See all results:";
	     locationSelect.appendChild(option);
	   }
	
	   function searchLocationsNear(center) {
	     clearLocations();
	
	     var radius = document.getElementById('radiusSelect').value;
	     var searchUrl = '<?php echo $this->url('locator'); ?>?isajax=1&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius;
	     downloadUrl(searchUrl, function(data) {
	       var xml = parseXml(data);
	       var markerNodes = xml.documentElement.getElementsByTagName("marker");
	       var bounds = new google.maps.LatLngBounds();
	       for (var i = 0; i < markerNodes.length; i++) {
	         var name = markerNodes[i].getAttribute("name");
	         var address = markerNodes[i].getAttribute("address");
	         var distance = parseFloat(markerNodes[i].getAttribute("distance"));
	         var latlng = new google.maps.LatLng(
	              parseFloat(markerNodes[i].getAttribute("lat")),
	              parseFloat(markerNodes[i].getAttribute("lng")));
	
	         createOption(name, distance, i);
	         createMarker(latlng, name, address);
	         bounds.extend(latlng);
	       }
	       map.fitBounds(bounds);
	       locationSelect.style.visibility = "visible";
	       locationSelect.style.display = "inline";
	       locationSelect.onchange = function() {
	         var markerNum = locationSelect.options[locationSelect.selectedIndex].value;
	         google.maps.event.trigger(markers[markerNum], 'click');
	       };
	      });
	    }
	
	    function createMarker(latlng, name, address) {
	      var html = "<b>" + name + "</b> <br/>" + address;
	      var marker = new google.maps.Marker({
	        map: map,
	        position: latlng
	      });
	      google.maps.event.addListener(marker, 'click', function() {
	        infoWindow.setContent(html);
	        infoWindow.open(map, marker);
	      });
	      markers.push(marker);
	    }
	
	    function createOption(name, distance, num) {
	      var option = document.createElement("option");
	      option.value = num;
	      option.innerHTML = name + "(" + distance.toFixed(1) + ")";
	      locationSelect.appendChild(option);
	    }
	
	    function downloadUrl(url, callback) {
	      var request = window.ActiveXObject ?
	          new ActiveXObject('Microsoft.XMLHTTP') :
	          new XMLHttpRequest;
	
	      request.onreadystatechange = function() {
	        if (request.readyState == 4) {
	          request.onreadystatechange = doNothing;
	          callback(request.responseText, request.status);
	        }
	      };
	
	      request.open('GET', url, true);
	      request.send(null);
	    }
	
	    function parseXml(str) {
	      if (window.ActiveXObject) {
	        var doc = new ActiveXObject('Microsoft.XMLDOM');
	        doc.loadXML(str);
	        return doc;
	      } else if (window.DOMParser) {
	        return (new DOMParser).parseFromString(str, 'text/xml');
	      }
	    }
	
	    function doNothing() {}
	    
		$(document).ready(function() {
			load();
			<?php if (isset($_GET['address'])): ?>
			document.getElementById("addressInput").value='<?php echo $_GET['address']; ?>';
			<?php endif; ?>
			<?php if (isset($_GET['distance'])): ?>
			document.getElementById("radiusSelect").value='<?php echo $_GET['distance']; ?>';
			<?php endif; ?>
			<?php if (isset($_GET['address']) || isset($_GET['distance'])): ?>
				searchLocations();
			<?php endif; ?>
			
			$('.btn_lightblue').bind('touchstart click', function(){
	            searchLocations();
	        });
		});
	    //]]>
	  </script>
	
	
	<div class="gallery">
	
		<?php echo $this->render('include/left_add.phtml'); ?>
		
		<div class="fright gallery_middle">
			<div class="search_categories">
				<form method="post" action="">
					<div style="margin:5px 0px;clear:both;overflow:hidden;text-align: left">
						<span>Address</span>
						<input type="text" id="addressInput" placeholder="Enter address..." />
					    <select id="radiusSelect" class="inputArea inputbox">
					    	<option value="10">10mi</option>
							<option value="15">15mi</option>
							<option value="20">20mi</option>
					    	<option value="25">25mi</option>
					    	<option value="50">50mi</option>
					    	<option value="75">75mi</option>
					      	<option value="100">100mi</option>
					      	<option value="200">200mi</option>
					    </select>
				    </div>
				    <div style="margin:5px 0px;clear:both;overflow:hidden;text-align: left">
					    <select id="locationSelect" style="visibility:hidden;display:none;margin-right:10px" class="inputArea inputbox"></select>
					    <button class="btn_lightblue upload_btn" type="button">
							<span style="background:none">GO</span>
						</button>
				    </div>
				</form>
			</div>
			<div style="clear:both;display:block;overflow:hidden">
				<div id="map" style="width: 58%;position:absolute;height:75%"></div>
			</div>
			<br />
			<br />
		</div>
		
	</div>
	<div style="clear:both;overflow:hidden"></div>
<?php endif; ?>