<script type="text/javascript">
//<!--
    $(document).ready(function() {
    
        $("input, textarea, select").not('.nostyle').uniform();
        $("#forgot_password_form").validate({
            rules: {
                email_address: {
                   required: true,
                   minlength: 5,
                   email:true,
                   maxlength: 255 
                }
            },
            messages: {
                email_address: {
                    required: "Email Address is required",
                    email: "Email address format is invalid",
                    minlength: "Please enter Email Address between 5 to 255 character!",
                    minlength: "Please enter Email Address between 5 to 255 character!"
                }
            }   
        });
    });
    //-->
</script>


<style type="text/css">
.wrapper.articlewrapper .row-fluid .span12.updateInfoBox .row-fluid .span12 .span6 .itemWrap label {
    width: 23%;
}
.wrapper.articlewrapper .row-fluid .span12.updateInfoBox .row-fluid .span12 .span6 {
    width: 72% !important;
}
</style>


<div class="wrapper articlewrapper">
    <div class="row-fluid">
        <div class="span12">
            <div class="span9 left">
                    <div class="row-fluid">
                        <div class="span12 top">
                            <div class="span12">
                                <div class="row-fluid">
                                    <div class="span12 title">
                                        Forgot Password
                                    </div>
                                    <div class="span12 desc borderNone">
                                        Here you can lorem ipsum dolor sit amet velit sit amet est. Curabitur tempor posuere libero, eget adipiscing lacus.
                                        Nunc sit amet urna ut leo sollicitudin interdum. In nibh quam, gravida in rhoncus non, placerat a lorem.
                                    </div>
                                                                        
                                    <div class="span12 updateInfoBox">
                                        <h3 class="border">Forgot Password?</h3>
                                        <div class="row-fluid">
                                            <div class="span12">
                                            <form class="form-signup" action="" method="post" id="forgot_password_form">  
                                               
                                                    
                                                    <div class="itemWrap clearfix">
                                                        <label style="text-align: left;" class="form-label" for="email_address">Email Address <em>*</em></label>                                                            
                                                        <div class="inputboxWrap">
                                                            <input class="inputbox" value="<?php echo isset($_POST['email_address']) ? $_POST['email_address'] : ''; ?>" id="email_address" name="email_address" type="text" />
                                                        </div>
                                                    </div>
                                                    
                                                
            
                                                <div class="span12">
                                                    <label class="none">&nbsp;</label>
                                                    <button type="submit" class="btn btn-primary">Submit</button>
                                                </div>
                                            </form>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <?php echo $this->render("include_main/right_sidebar_home.phtml"); ?>
        </div>
    </div>   
</div>                