<script type="text/javascript">
//<!--
    $(document).ready(function() {
    
        $("input, textarea, select").not('.nostyle').uniform();
        $("#forgot_password_form").validate({
            rules: {
                password: {
                    required: true,
                    minlength: 4,
                    maxlength:255
                },
                confirm_password: {
                    required: true,
                    minlength: 4,
                    maxlength:255,
                    equalTo: '#password'
                }   
            },
            messages: {
               
                password: {
                    required: "Password is required",
                    minlength: "Please enter Password between 4 to 255 character!",
                    minlength: "Please enter Password between 4 to 255 character!"
                },
                confirm_password: {
                    required: "Confirm Password is required",
                    minlength: "Please enter Confirm Password between 4 to 255 character!",
                    minlength: "Please enter Confirm Password between 4 to 255 character!",
                    equalTo: 'Confirm Password and Password is not same'
                }
            }   
        });
    });
    //-->
</script>


<style type="text/css">
.wrapper.articlewrapper .row-fluid .span12.updateInfoBox .row-fluid .span12 .span6 .itemWrap label {
    width: 23%;
}
.wrapper.articlewrapper .row-fluid .span12.updateInfoBox .row-fluid .span12 .span6 {
    width: 72% !important;
}
</style>


<div class="wrapper articlewrapper">
    <div class="row-fluid">
        <div class="span12">
            <div class="span9 left">
                    <div class="row-fluid">
                        <div class="span12 top">
                            <div class="span12">
                                <div class="row-fluid">
                                    <div class="span12 title">
                                        Change Your Password
                                    </div>
                                    <div class="span12 desc borderNone">
                                        Here you can lorem ipsum dolor sit amet velit sit amet est. Curabitur tempor posuere libero, eget adipiscing lacus.
                                        Nunc sit amet urna ut leo sollicitudin interdum. In nibh quam, gravida in rhoncus non, placerat a lorem.
                                    </div>
                                                                        
                                    <div class="span12 updateInfoBox">
                                        <h3 class="border">Change Your Password?</h3>
                                        <?php if ($this->userInfo): ?>
                                        <div class="row-fluid">
                                            <div class="span12">
                                            <form class="form-signup" action="" method="post" id="forgot_password_form">  
                                            
                                                <div class="span7">
                                                    
                                                    <div class="itemWrap clearfix">
                                                        <label style="text-align: left;" class="form-label" for="password">Password <em>*</em></label>                                                            
                                                        <div class="inputboxWrap">
                                                            <input class="inputbox" value="" id="password" name="password" type="password" />
                                                        </div>
                                                    </div>
													<div class="itemWrap clearfix">
                                                        <label style="text-align: left;" class="form-label" for="confirm_password">Confirm Password <em>*</em></label>                                                            
                                                        <div class="inputboxWrap">
                                                            <input class="inputbox" value="" id="confirm_password" name="confirm_password" type="password" />
                                                        </div>
                                                    </div>
													<div class="itemWrap clearfix">
                                                        <label style="text-align: left;" class="form-label">&nbsp;</label>                                                            
														<button type="submit" class="btn btn-primary marginR10">Submit</button>
                                                    </div>
                                                </div>
                                                
                                            </form>
                                            </div>
                                        </div>
                                        <?php else: ?>
                                            <div class="row-fluid">
                                                <div class="span12">
                                                    We could not take your request due to expired your activation key or you did not request us for change password.
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    
                                    
                                    
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <?php echo $this->render("include_main/right_sidebar_home.phtml"); ?>
        </div>
    </div>   
</div>                