<?php $url = $this->getSettings('website_url'); ?>
<script type="text/javascript" src="<?php echo $url.$this->basePath('assets/ckeditor/ckeditor.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $url.$this->basePath('assets/ckeditor/plugins/ckfinder/ckfinder.js'); ?>"></script>
<script type="text/javascript">
    //<!--
    $(document).ready(function() {
        $("#page").validate({
            rules: {
                page_title: {
                   required: true,
                   maxlength: 255
                },
                page_content: {
                   required: true
                },
                block_identifier: {
					required: true
				},
                is_active: {
                    required: true,
                    digits:true
                }
            },
            messages: {
                page_title: {
                    required: "Block title is required",
                    maxlength: "Block title is bigger"
                },
                page_content: {
                    required: "Block content is required"
                },
                block_identifier: {
                    required: "Identifier is required"
                },
                is_active: {
                    required: "Status is required",
                    digits: "Please slect only digit"
                }
            }   
        });
    });
    //-->
</script>
<div class="row-fluid">

    <div class="span10">
    
        <div class="heading">
            <?php if ($this->editBlockInfo): ?>
                <h3>Edit CMS Block</h3>
            <?php else: ?>
                <h3>Add New CMS Block</h3>
            <?php endif; ?>
        </div><!-- End .heading-->
        
        <div class="backlink">
            <a href="<?php echo $this->url('cms', array('action' => 'block')); ?>">Back to Cms Block List</a>
        </div>

    </div>

</div>
               
<div class="row-fluid">

    <div class="span10 tableBox">
        
        <div class="row-fluid">
                 
            <div class="span12">
            
                <div class="usertitle">
                    Cms Block
                </div>
                    
                    <form class="form-horizontal" id="page" method="post" action="" enctype="multipart/form-data">
                        <div class="rowfluidWrap">
                        <div class="row-fluid">  
							<div class="span4">                                                                      
	                        	<div class="form-row row-fluid">
	                                <div class="span12">
	                                    <div class="row-fluid">
	                                        <label class="form-label span5" for="block_title" style="text-align: left;">Title:*</em></label>
	                                        <input class="span7" id="block_title" name="block_title" type="text" value="<?php echo isset($this->editBlockInfo[0]['block_title']) ? $this->editBlockInfo[0]['block_title']:''; ?>" />
	                                    </div>
	                                </div>
	                            </div>
	                            
	                            
	                            <div class="form-row row-fluid">
	                                <div class="span12">
	                                    <div class="row-fluid">
	                                        <label class="form-label span5" for="block_identifier" style="text-align: left;">Identifier:*</em></label>
	                                        <input class="span7" id="block_identifier" name="block_identifier" type="text" value="<?php echo isset($this->editBlockInfo[0]['block_identifier']) ? $this->editBlockInfo[0]['block_identifier']:''; ?>" />
	                                    </div>
	                                </div>
	                            </div>
	                            
	                            <div class="form-row row-fluid">
	                                <div class="span12">
	                                    <div class="row-fluid">
	                                        <label class="form-label span5" for="status">Status:*</label>
	                                        <div class="role">
	                                            <select name="block_status" id="block_status">
	                                                <option value="1" <?php echo (isset($this->editBlockInfo[0]['block_status'])&& $this->editBlockInfo[0]['block_status']==1) ? 'selected':''; ?>>Active</option>
	                                                <option value="0" <?php echo (isset($this->editBlockInfo[0]['block_status'])&& $this->editBlockInfo[0]['block_status']==0) ? 'selected':''; ?>>In Active</option>
	                                            </select>
	                                        </div>
	                                    </div>
	                                </div>
	                            </div>    
	                            
	                            <div class="form-row row-fluid" style="display:none">
	                                <div class="span12">
	                                    <div class="row-fluid">
	                                        <label class="form-label span5" for="block_position">Postion:*</label>
	                                        <div class="role">
	                                            <select name="block_position" id="block_position">
	                                                <option value="2" <?php echo (isset($this->editBlockInfo[0]['block_position'])&& $this->editBlockInfo[0]['block_position']==2) ? 'selected':''; ?>>Left</option>
	                                                <option value="1" <?php echo (isset($this->editBlockInfo[0]['block_position'])&& $this->editBlockInfo[0]['block_position']==1) ? 'selected':''; ?>>Right</option>
	                                            </select>
	                                        </div>
	                                    </div>
	                                </div>
	                            </div>             
	                            
	                            
	                            <div class="form-row row-fluid" style="display:none">
	                                <div class="span12">
	                                    <div class="row-fluid">
	                                        <label class="form-label span5" for="block_ordering" style="text-align: left;">Block Ordering:*</em></label>
	                                        <input class="span3" id="block_ordering" name="block_ordering" type="text" value="<?php echo isset($this->editBlockInfo[0]['block_ordering']) ? $this->editBlockInfo[0]['block_ordering']:0; ?>" />
	                                    </div>
	                                </div>
	                            </div>                   
                            </div>                                                    
                            
                            
                            <div class="span8">
	                            <div class="form-row row-fluid">
	                                <div class="span12">
	                                    <div class="row-fluid">
	                                        <label class="form-label span5" for="block_content" style="text-align: left;margin:0;">Content:*</label>
	                                        <br />
	                                        <br />
	                                        <textarea class="span7" id="block_content" name="block_content" rows="10" cols="40"><?php echo isset($this->editBlockInfo[0]['block_content']) ? $this->editBlockInfo[0]['block_content']:''; ?></textarea>
	                                        <script type="text/javascript">
	                                			//<![CDATA[
	                                				var editor = CKEDITOR.replace( 'block_content',
	                                					{
	                                						fullPage : false,
	                                						extraPlugins : 'docprops',
	                                                        toolbar: [
	                                                        	{ name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
	                                                        	{ name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
	                                                        	{ name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ] },
	                                                        	{ name: 'tools', items: [ 'Maximize' ] },
	                                                        	{ name: 'document', groups: [ 'mode', 'document', 'doctools' ], items: [ 'Source' ] },
	                                                        	{ name: 'others', items: [ '-' ] },
	                                                        	'/',
	                                                        	{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
	                                                        	{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ] },
	                                                        	{ name: 'styles', items: [ 'Styles', 'Format' ] },
	                                                        	{ name: 'about', items: [ 'About' ] }
	                                                        ],
	                                                        filebrowserBrowseUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/ckfinder.html'); ?>',
	                                                     	filebrowserImageBrowseUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/ckfinder.html?type=Images'); ?>',
	                                                     	filebrowserFlashBrowseUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/ckfinder.html?type=Flash'); ?>',
	                                                     	filebrowserUploadUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files'); ?>',
	                                                     	filebrowserImageUploadUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'); ?>',
	                                                     	filebrowserFlashUploadUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'); ?>',
	                                                     	filebrowserWindowWidth : '700',
	                                                     	filebrowserWindowHeight : '500'
	                                					});
	                                                CKFinder.setupCKEditor( editor, '<?php echo $this->basePath('media'); ?>' ) ;
	                                
	                                			//]]>
	                             			</script>
	                                    </div>
	                                </div>
	                            </div> 
                            </div>
                             
                        
                        </div>
                        </div>
                        
                        <div class="form-row row-fluid">
                            
                            <div class="span12">
                                <div class="row-fluid">
                                    <div class="form-actions">
                                        <div class="controls">
                                            <button class="btn btn-primary pull-right marginL10 btn-danger" style="margin-left:20px" type="button" onclick="window.location = '<?php echo $this->url('cms', array('action' => 'block')); ?>';">Cancel</button>
                                            <button id="successR" type="submit" class="btn marginR10 btn-success pull-right">Save</button>
                                            <!--button id="errorR" type="submit" class="btn marginR10">Save</button-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        
                    </form>
                    
                </div>                         
            
        </div>
        
    </div>
    
</div>
