<script type="text/javascript">
    //<!--
    var ids = [];
    
    $(document).ready(function() {
       $('.id_checkbox').click(function() {
            if (this.checked) {
                 ids.push(this.value);
            } else {
                var index = ids.indexOf(this.value); 
                if (index != -1)
                    ids.splice(index,1);
            }
            $('input[name=ids]').val(ids);
       }); 
    });
    
    function showStatus(value) {
        if (value == 'status')
            $('#status').css('display', 'inline-block');
        else
            $('#status').hide();
    }
    
    function checkPageIds() {
        if ($('input[name=ids]').val() != '') {
            return true;
        }
        alert('Please select page');
        return false;
    }
    
    function toggleChecked(status) {
        $(".id_checkbox").each(function() {
            $(this).attr("checked",status);
            if(status){
              $(this).parent().addClass('checked');  
              ids.push(this.value);
            } else {
              $(this).parent().removeClass('checked');
              var index = ids.indexOf(this.value); 
                if (index != -1)
                    ids.splice(index,1);
            }
        })
        $('input[name=ids]').val(ids);
        //onclick="toggleChecked(this.checked)"
    }
    //-->
</script>

<style type="text/css">
#uniform-status {
    display: none;
}
</style>

<div class="row-fluid">

    <div class="span10">
    
        <div class="heading">

            <h3>CMS Page</h3>                    

        </div><!-- End .heading-->

    </div>

</div>

<div class="row-fluid">

    <div class="span10 tableBox">
        
        <div class="row-fluid">
                 
            <div class="box gradient admin">

                <div class="title">
                    <div class="selectbox">   
                                  
                            <form method="post" action="<?php echo $this->url('cms', array('action' => 'mass-page-modification')); ?>">
                                <select name="action" onchange="showStatus(this.value)">
                                    <option selected="selected">Choose action</option>
                                    <option value="delete">Delete</option>
                                    <option value="status">Change Status</option>
                                </select>
                                <select name="status" id="status" style="display:none">
                                    <option selected="selected">Change Status</option>
                                    <option value="1">Active</option>
                                    <option value="0">In Active</option>
                                </select>
                                <input type="hidden" name="ids" />
                                <button type="submit" onclick="return checkPageIds();" class="btn btn-inverse">Submit</button>
                                <a href="<?php echo $this->url('cms', array('action' => 'new-page')); ?>" class="btn btn-success">Add New Page</a>
                               
                            </form>
                       
                    </div>
                    
                            
                </div>
                <div class="content noPad clearfix">
                    <div class="scrollable">
                       <table cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                         <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" name="optionsCheckboxList1" value="option1" class="styled" onclick="toggleChecked(this.checked)" />
                                </th>
                                <th>Title</th>
                                <th>Identifier</th>
                                <th>Status</th>
                                <th>Created Date</th>
                                <th>Updated Date</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php 
                            if (count($this->paginator)): 
                                $iterator = 1;
                                foreach ($this->paginator as $item): 
                        ?>
                            <tr class="<?php if ($iterator++%2 == 0) echo 'even'; else echo 'odd'; ?>">
                                <td>
                                    <input type="checkbox" class="id_checkbox" name="id[]" value="<?php echo $item['page_id']; ?>" class="styled" />
                                </td>
                                <td><?php echo $item['page_title']; ?></td>
                                <td><?php echo $item['page_identifier']; ?></td>
                                <td><?php echo $item['is_active'] == 1? 'Active':'In Active'; ?></td>
                                <td><?php echo date('d/m/Y', strtotime($item['created_date'])); ?></td>
                                <td><?php echo date('d/m/Y', strtotime($item['updated_date'])); ?></td>
                                <td>
                                    <a href="<?php echo $this->url('cms', array('action' => 'edit-page', 'id' => $item['page_id'])); ?>" class="btn btn-success">Edit Page</a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="6">--No data found--</td>
                            </tr>
                        <?php endif; ?>
                    
                        </tbody>
                    </table>
                    
                    <?php echo $this->paginationControl(
                                                        $this->paginator,
                                                        'Sliding',
                                                        'include/pagination_control.phtml',
                                                        array('route' => 'cms', 'action' => 'block')
                            ); 
                    ?>
                    
                    </div>
                </div>

            </div><!-- End .box -->                           
            
        </div>
        
    </div>
    
</div>  