<script type="text/javascript">
//<!--
    $(document).ready(function() {
        $("#forgot_password").validate({
            rules: {
                email_address: {
                    required: true,
                    email: true,
                    minlength: 4
                }  
            },
            messages: {
                email_address: {
                    required: "Fill me please",
                    minlength: "My name is bigger",
                    email: 'Invalid email address'
                }
            }   
        });
    });
    //-->
</script>

<div class="container-fluid">
    <div class="loginContainer">
        <form class="form-horizontal" action="" method="post" id="forgot_password">
            <div class="form-row row-fluid">
                <div class="span12">
                    <div class="row-fluid">
                        <label class="form-label span12" for="email">
                            Enter your email address:
                            <span class="icon16 entypo-icon-email  right gray marginR10"></span>
                        </label>
                        <input class="span12" id="email_address" type="text" name="email_address" value="" />
                    </div>
                </div>
            </div>

            <div class="form-row row-fluid">                       
                <div class="span12">
                    <div class="row-fluid">
                        <div class="form-actions">
                        <div class="span12 controls">
                            <a href="<?php echo $this->url('admin_login'); ?>">Back to login</a>
                            <button type="submit" class="btn btn-info right" id="loginBtn"><span class="icon16 icomoon-icon-enter white"></span> Send Password</button>
                        </div>
                        </div>
                    </div>
                </div> 
            </div>

        </form>
    </div>
</div><!-- End .container-fluid -->
    
