<script type="text/javascript">
//<!--
    $(document).ready(function() {
    
        $("input, textarea, select").not('.nostyle').uniform();
        $("#user_form").validate({
            rules: {
                username: {
                    required: true,
                    minlength: 4,
                    maxlength:255
                },
                password: {
                    required: true,
                    minlength: 4,
                    maxlength:255
                }
            },
            messages: {
                username: {
                    required: "Username is required",
                    minlength: "Please enter Username between 4 to 255 character!",
                    minlength: "Please enter Username between 4 to 255 character!"
                },
                password: {
                    required: "Password is required",
                    minlength: "Please enter Password between 4 to 255 character!",
                    minlength: "Please enter Password between 4 to 255 character!"
                }
            }   
        });
    });
    //-->
</script>


<style type="text/css">
.wrapper.articlewrapper .row-fluid .span12.updateInfoBox .row-fluid .span12 .span6 .itemWrap label {
    width: 23%;
}
.wrapper.articlewrapper .row-fluid .span12.updateInfoBox .row-fluid .span12 .span6 {
    width: 65% !important;
}
</style>

<div class="wrapper articlewrapper">
    <div class="row-fluid">
        <div class="span12">
            <div class="span9 left">
                    <div class="row-fluid">
                        <div class="span12 top">
                            <div class="span12">
                                <div class="row-fluid">
                                    <div class="span12 title">
                                        Login
                                    </div>
                                    <div class="span12 desc borderNone">
                                        Here you can lorem ipsum dolor sit amet velit sit amet est. Curabitur tempor posuere libero, eget adipiscing lacus.
                                        Nunc sit amet urna ut leo sollicitudin interdum. In nibh quam,Curabitur tempor posuere libero, eget adipiscing lacus.
                                        Nunc sit amet urna ut leo sollicitudin interdum. In nibh quam,Curabitur tempor posuere libero, eget adipiscing lacus.
                                        Nunc sit amet urna ut leo sollicitudin interdum. In nibh quam, gravida in rhoncus non, placerat a lorem.
                                    </div>
                                                                        
                                    <div class="span12 updateInfoBox">
                                        <h3 class="border">Login Form</h3>
                                        <div class="row-fluid">
                                            <div class="span12">
                                            <form class="form-signup" action="" method="post" id="user_form">  
                                                <div class="span6">
                                                    <div class="itemWrap clearfix">
                                                        <label style="text-align: left;" class="form-label" for="username">User name <em>*</em></label>                                                            
                                                        <div class="inputboxWrap">
                                                            <input class="span6 inputbox" id="username" value="<?php echo isset($_POST['username']) ? $_POST['username'] : ''; ?>" name="username" type="text" />
                                                        </div>
                                                    </div>
                                                    <div class="itemWrap clearfix">
                                                        <label style="text-align: left;" class="form-label" for="password">Password <em>*</em></label>                                                            
                                                        <div class="inputboxWrap">
                                                            <input class="span6 inputbox" id="password" name="password" type="password" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="span12">
                                                    <button type="submit" class="btn btn-primary pull-right marginR10">Login</button>
                                                </div>
                                            </form>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <?php echo $this->render("include_main/right_sidebar_home.phtml"); ?>
        </div>
    </div>   
</div>                