
<div class="row-fluid">

    <div class="span10">
    
        <div class="heading">

            <h3>Dashboard</h3>                    

        </div><!-- End .heading-->

    </div>

</div>

<div class="row-fluid">

    <div class="span10 tableBox">
        
        <div class="row-fluid">

            <div class="span8">
            
                <div class="row-fluid">
                 
                    <div class="box">

                        <div class="title">

                            <h4>
                                <span class="">
                                    <img alt="" src="<?php echo $this->basePath('assets/design/admin/images/box_title_icon_bg.jpg'); ?>" />
                                </span>
                                <span>Order Graph of 2014</span>
                            </h4>
                            <a class="minimize" href="#" style="display: none;">Minimize</a>
                        </div>
                        <div class="content">
                            <script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
                            <script src="<?php echo $this->basePath('assets/js/exporting.js'); ?>"></script>
                            <script type="text/javascript">
                            $(function () {
                                $('.auto-update-chart').highcharts({
                                    chart: {
                                        plotBackgroundColor: null,
                                        plotBorderWidth: null,
                                        plotShadow: false
                                    },
                                    title: {
                                        text: ''
                                    },
                                    plotOptions: {
                                        pie: {
                                            allowPointSelect: true,
                                            cursor: 'pointer',
                                            dataLabels: {
                                                enabled: true,
                                                color: '#000000',
                                                connectorColor: '#000000',
                                            }
                                        }
                                    },
                                    series: [{
                                        type: 'pie',
                                        name: 'Year Wise ',
                                        data: [
                                            ['January',   45.0],
                                            
                                            {
                                                name: 'May',
                                                y: 12.8,
                                                sliced: true,
                                                selected: true
                                            },
                                            ['June',    8.5],
                                            ['July',       26.8],
                                            ['December',   0.7]
                                        ]
                                    }]
                                });
                            });
                            </script>                            
                            <div class="row-fluid">
                                <div class="auto-update-chart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                            </div>
                                                                                                                    
                        </div>

                    </div><!-- End .box -->
                 
                 </div>  
            
            </div>
            
            <div class="span4">
                
                <div class="box">
        
                    <div class="title">

                        <h4>
                            <span class="">
								<img alt="" src="<?php echo $this->basePath('assets/design/admin/images/box_title_icon_bg.jpg'); ?>" />
							</span>
                            <span>Last 5 Orders</span>
                        </h4>
                        <a class="minimize" href="#" style="display: none;">Minimize</a>
                    </div>
                    <div class="content">
                         <div class="scrollable">
		                      <table cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
		                        <thead>
		                            <tr>
		                                <th style="border-top:0">Customer</th>
		                                <th style="border-top:0">Item</th>
		                                <th style="border-top:0">Grand Total</th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                            <tr>
		                                <td>Jahangir Alam</td>
		                                <td>1</td>
		                                <td>$25.00</td>
		                            </tr>
		                            <tr>
		                                <td>Jahangir Alam</td>
		                                <td>1</td>
		                                <td>$25.00</td>
		                            </tr>
		                        </tbody>
							</table>
						</div>
                        
                    </div>

                </div><!-- End .box -->
                
                <div class="box">
        
                    <div class="title">

                        <h4>
                            <span class="">
								<img alt="" src="<?php echo $this->basePath('assets/design/admin/images/box_title_icon_bg.jpg'); ?>" />
							</span>
                            <span>New Customer</span>
                        </h4>
                        <a class="minimize" href="#" style="display: none;">Minimize</a>
                    </div>
                    <div class="content">
                         <div class="scrollable">
		                    <table cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
		                        <thead>
		                            <tr>
		                                <th style="border-top:0">First Name</th>
		                                <th style="border-top:0">Last Name</th>
		                                <th style="border-top:0">Join Date</th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                            <tr>
		                                <td>Jahangir</td>
		                                <td>Alam</td>
		                                <td>25-04-2014</td>
		                            </tr>
		                            <tr>
		                                <td>Jahangir</td>
		                                <td>Alam</td>
		                                <td>25-04-2014</td>
		                            </tr>
		                        </tbody>
							</table>
						</div>
                        
                    </div>

                </div><!-- End .box -->
                
            </div>
            
        </div>
        
    </div>

</div>