<script type="text/javascript">
    //<!--
    $(document).ready(function() {
         $("#category").validate({
            rules: {
                name: {
                   required: true,
                   maxlength: 255
                },
                is_active: {
                    required: true,
                    digits:true
                }
            },
            messages: {
                name: {
                    required: "Category name is required"
                },
                is_active: {
                    required: "Status is required"
                }
            }   
        });
    });
    //-->
</script>

<div class="main">

	<div class="page_title">
        <h3><?php echo $this->title; ?></h3>
        <a href="<?php echo $this->url('category', array('action' => 'index')); ?>">Back to Category List</a>
    </div>
   
               
	<div class="content"> 

        <form class="form-horizontal" id="category" method="post" action="" enctype="multipart/form-data">

            <div class="row">
                <label class="form-label span5" for="name" style="text-align: left;">Name:*</label>
                <input class="inputArea" id="name" name="name" type="text" value="<?php echo isset($this->category[0]['name']) ? $this->category[0]['name'] : ''; ?>"  />
            </div>
           
		    <div class="row">
                <label class="form-label span5" for="status">Status:*</label>
                <div class="role">
                    <select name="is_active" id="is_active" style="width: 170px !important;">
                        <option value="1" <?php echo (isset($this->category[0]['is_active'])&& $this->category[0]['is_active'] == 1) ? 'selected' : ''; ?>>Active</option>
                        <option value="0">In Active</option>
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="form-actions">
                    <div class="controls">
                        <button class="btn btn-primary pull-right marginL10 btn-danger" type="button" style="margin-left:20px" onclick="window.location='<?php echo $this->url('category', array('action' => 'index')); ?>';">Cancel</button>
                        <button id="successR" type="submit" class="btn marginR10 btn-success pull-right">Save</button>
                    </div>
                </div>
            </div>
                
                    
        </form>
            
    </div>                         
    
</div>