<script type="text/javascript">
    //<!--
    var oid = '<?php echo isset($this->attribute[0]['option_id']) ? $this->attribute[0]['option_id'] : '0'; ?>';
    var gid = '<?php echo isset($this->attribute[0]['group_id']) ? $this->attribute[0]['group_id'] : '0'; ?>';
    $(document).ready(function() {
         $("#attribute_form").validate({
            rules: {
                name: {
                   required: true,
                   maxlength: 255
                },
                is_active: {
                    required: true,
                    digits:true
                }
            },
            messages: {
                name: {
                    required: "Attribute name is required"
                },
                is_active: {
                    required: "Status is required"
                }
            }   
        });
        
        $('#allow_level').bind('touchstart click', function(){
            if (this.checked) {
                 $('#attribute_sublevel').show();
            } else {
				$('#attribute_sublevel').hide();
			}
       });
       
       $('#add_row').bind('touchstart click', function(){
       	
 			var table = document.getElementById('dataTable');
 			var table1 = document.getElementById('datatable_row_table');
 			
            var rowCount = table.rows.length;
            var row = table.insertRow(rowCount);
 
            var colCount = table.rows[0].cells.length;
 
            for(var i=0; i<colCount; i++) {
 
                var newcell = row.insertCell(i);

                newcell.innerHTML = table1.rows[0].cells[i].innerHTML;
                //alert(newcell.childNodes);
                switch(newcell.childNodes[0].type) {
                    case "text":
                            newcell.childNodes[0].value = "";
                            break;
                    case "checkbox":
                            newcell.childNodes[0].checked = false;
                            break;
                    case "select-one":
                            newcell.childNodes[0].selectedIndex = 0;
                            break;
                }
            }
       });
	   
	   $('#delete_row').bind('touchstart click', function(){
			try {
	            var table = document.getElementById('dataTable');
	            var rowCount = table.rows.length;
	 
	            for(var i=0; i<rowCount; i++) {
	                var row = table.rows[i];
	                var chkbox = row.cells[0].childNodes[0];
	                if(null != chkbox && true == chkbox.checked) {
	                    if(rowCount <= 2) {
	                        alert("Cannot delete all the rows.");
	                        break;
	                    }
	                    table.deleteRow(i);
	                    rowCount--;
	                    i--;
	                }
	 
	 
	            }
            } catch(e) {
                alert(e);
            }
       }); 
       
       loadOption(gid);
    });
    
    function loadOption(value) {
		$.ajax({
		  		url:"<?php echo $this->url('category', array('action' => 'attribute-group-option')); ?>?isAjax=1&gid="+value+'&oid='+oid,
				success:function(html){
			    	jQuery("#option_region").html(html);
			    }
		});
	}
	
	function showhideAttributeSublevel(value) {
		if (value == 1) {
			jQuery('#attribute_sublevel').show();
		} else if (value == 2) {
			jQuery('#attribute_sublevel').hide();
		}
	}
	
    //-->
</script>

<div class="main">

	<div class="page_title">
        <h3><?php echo $this->title; ?></h3>
        <a href="<?php echo $this->url('category', array('action' => 'attribute')); ?>">Back to Attribute List</a>
    </div>
   
               
	<div class="content"> 

        <form class="form-horizontal" id="attribute_form" method="post" action="" enctype="multipart/form-data">

            <div class="row">
                <label class="form-label span5" for="name" style="text-align: left;">Name:*</label>
                <input class="inputArea" id="name" name="name" type="text" value="<?php echo isset($this->attribute[0]['name']) ? $this->attribute[0]['name'] : ''; ?>"  />
            </div>
            
            <div class="row">
                <label class="form-label span5" for="status">Status:*</label>
                <div class="role">
                    <select name="is_active" id="is_active" style="width: 170px !important;">
                        <option value="1" <?php echo (isset($this->attribute[0]['is_active'])&& $this->attribute[0]['is_active'] == 1) ? 'selected' : ''; ?>>Active</option>
                        <option value="0">In Active</option>
                    </select>
                </div>
            </div>
            
            <div class="row">
                <label class="form-label span5" for="input_type">Input Type:*</label>
                <div class="role">
                    <select name="input_type" id="input_type" style="width: 170px !important;" onchange="showhideAttributeSublevel(this.value)">
                        <option value="1" <?php echo (isset($this->attribute[0]['input_type'])&& $this->attribute[0]['input_type'] == 1) ? 'selected' : ''; ?>>Dropdawn</option>
                        <option value="2" <?php echo (isset($this->attribute[0]['input_type'])&& $this->attribute[0]['input_type'] == 2) ? 'selected' : ''; ?>>Textbox</option>
                    </select>
                </div>
            </div>
            
            
            <div class="row">
                <label class="form-label span5" for="group_id">Attribute Group:*</label>
                <div class="role">
                    <select name="group_id" id="group_id" style="width: 170px !important;" onchange="loadOption(this.value)">
                    	<option value="">--Select Group--</option>
			            <?php foreach($this->groupList as $group): ?>
			            	<option value="<?php echo $group['id']; ?>" <?php echo (isset($this->attribute[0]['group_id'])&& $this->attribute[0]['group_id']==$group['id']) ? 'selected="selected"' : ''; ?>><?php echo $group['name']; ?></option>
			            <?php endforeach; ?>
            		</select>
                </div>
            </div>
            
            <div class="row" id="option_region">
			</div>
			
            
            <div class="row" id="attribute_sublevel">
            	<label class="form-label span5" for="group_id">Attribute Option:</label>
                <div class="role">
	            	<input type="button" id="add_row" value="Add Row"  class="btn marginR10" />
	    			<input type="button" id="delete_row" value="Delete Row" class="btn marginR10" />
	 			    <table id="dataTable" style="width:100%">
	 			    	<tr>
	 			    		<td>Option</td>
						 	<td>Option Name</td>
						 	<td>Sub Level<br />(Use Comma for seperate)</td>
						 </tr>
	 			    	<?php if ($this->optionData) : ?>
	 			    		<?php foreach ($this->optionData as $option): ?>
					        <tr>
					        	<td><input type="checkbox" name="chk" /></td>
					            <td><input class="inputArea" type="text" name="option_name[<?php echo $option['option_index']-1 ?>]" value="<?php echo $option['option_name']; ?>" /></td>
					            <td><input class="inputArea" type="text" name="subitem[<?php echo $option['option_index']-1 ?>]" value="<?php echo $option['subitem']; ?>" /></td>
					        </tr>
					        <?php endforeach; ?>
					    <?php else: ?>
					    	<tr>
					    		<td><input type="checkbox" name="chk" /></td>
					            <td><input class="inputArea" type="text" name="option_name[]" /></td>
					            <td><input class="inputArea" type="text" name="subitem[]" /></td>
					        </tr>
					    <?php endif; ?>
				    </table>
			    </div>
			</div>
           
            <div class="row">
                <div class="form-actions">
                    <div class="controls">
                        <button class="btn btn-primary pull-right marginL10 btn-danger" type="button" style="margin-left:20px" onclick="window.location='<?php echo $this->url('category', array('action' => 'attribute')); ?>';">Cancel</button>
                        <button id="successR" type="submit" class="btn marginR10 btn-success pull-right">Save</button>
                    </div>
                </div>
            </div>
                
                    
        </form>
        
        <div style="display:none" id="datatable_row">
        	<table id="datatable_row_table">
        		<tr>
		    		<td><input type="checkbox" name="chk" /></td>
		            <td><input class="inputArea" type="text" name="option_name[]" /></td>
		            <td><input class="inputArea" type="text" name="subitem[]" /></td>
	            </tr>
	        </table>
		</div>
            
    </div>                         
    
</div>