<?php $url = $this->getSettings('website_url'); ?>
<?php $paypal = $this->getSettings('paypal_business_email_address'); ?>
<?php $paypalPayment = $this->getSettings('paypal_payment'); ?>
<?php $paypalUrl = $paypalPayment == 'sandbox' ? 'https://www.sandbox.paypal.com/cgi-bin/webscr' : 'https://www.paypal.com/cgi-bin/webscr'; ?>

<script type="text/javascript">
//<!--
	$(document).ready(function() {
    	$( ".delete_upload" ).live( "touchstart click", function(e) {
        	return confirm('Do you want to delete this item permanently?');
        });
    });
    //-->
</script>

<div class="gallery">
	<?php echo $this->render('include/navigation.phtml'); ?>
	<div class="fright gallery_middle">
		<?php echo $this->render('include/add.phtml'); ?>
		
		<div class="list_of_gallery fleft">
			<div class="page_title">
				<h3><?php echo $this->title; ?></h3>
			</div>
			
			<div class="subscription_form">
				<table width="100%">
	  		
		  			<tr class="header">
						<td width="15%" align="left">
							&nbsp;
						</td>
						<td width="60%" align="left">
							UPLOADED PRODUCTS:
						</td>
						<td width="10%" align="center">
							<p>CHARGE</p>
						</td>
						<td width="15%" align="center">&nbsp;</td>
					</tr>  
					<?php 
					$total = 0;
					$cartId = '';
					foreach ($this->dealerCartInfo as $cart): ?>
					<tr>
						<?php
						$image = '';
						$cartId .= $cart['cart_id'].',';
						if ($cart['image']) { 
							$image = $cart['image']; 
						}
						?>
						<td width="15%" align="left" class="image">
							<img src="<?php echo $image != '' ? $this->basePath('media/product/'.$image) : 'http://placehold.it/300x300/'; ?>" alt="<?php echo $cart['name']; ?>" />
						</td>
						<?php 
						$currency = '';
						if ($cart['currency'] == 'euro') { 
							$currency = '&euro; '; 
						} elseif ($cart['currency'] == 'dollar') { 
							$currency = '$ '; 
						}  elseif ($cart['currency'] == 'fr') { 
							$currency = 'fr. '; 
						}
						?>
						<td width="60%" align="left" class="gray_bg">
							<div>
								<?php echo $cart['name']; ?>
								<span style="float:right;">
									value:<?php echo $currency; ?> <?php echo number_format($cart['upload_price'], 2); ?>
								</span>
							</div>
						</td>
						<td width="10%" align="center" class="gray_bg">
							<p>
							<?php echo $currency; ?> 
							<?php 
							$total += $cart['cart_price'];
							echo number_format($cart['cart_price'], 2); ?>
							</p>
						</td>
						<td width="15%" align="center">
							<a href="#">edit</a>&nbsp;&nbsp;
							<a class="delete_upload" href="<?php echo $this->url('delete_upload', array('id' => $cart['id'])); ?>" style="color:red">delete</a>
						</td>
					</tr>  	
					<?php endforeach; ?>
					
					<tr>
						<td width="15%" align="left">
							&nbsp;
						</td>
						<td width="60%" align="right">
						TOTAL
						</td>
						<td width="10%" align="center" class="gray_bg">
							<p><?php echo number_format($total, 2); ?>&euro;</p>
						</td>
						<td width="15%" align="center">&nbsp;</td>
					</tr>  
				
				
					<tr>
						<td width="15%" align="left">
							&nbsp;
						</td>
						<td width="60%" align="left">
						SELECT
						</td>
						<td width="10%" align="center">
							&nbsp;
						</td>
						<td width="15%" align="center">&nbsp;</td>
					</tr>  
				
					<tr>
						<td width="15%" align="left">
							&nbsp;
						</td>
						<td width="60%" align="left">
							<img src="<?php echo $url.$this->basePath('assets/design/frontend/default/images/paypal_logo.png'); ?>" border="0" alt="PayPal Logo" />
							<img src="<?php echo $url.$this->basePath('assets/design/frontend/default/images/visa_logo.png'); ?>" border="0" alt="Credit Card Logos" />
							<!--input type="radio" name="payment_method" value="visa" /-->
						</td>
						<td width="10%" align="center">
							<form name="_xclick" action="<?php echo $paypalUrl; ?>" method="post">
								
								<!-- Specify a Buy Now button. -->
								<input type="hidden" name="cmd" value="_xclick">
								
								<!-- Identify your business so that you can collect the payments. -->
								<input type="hidden" name="business" value="<?php echo $paypal; ?>" />
								
								<!-- Specify details about the item that buyers purchase. -->
								<input type="hidden" name="item_name" value="Pay amount for Upload Item">
								<input type="hidden" name="amount" value="<?php echo number_format($total, 2); ?>">
								<input type="hidden" name="currency_code" value="EUR" />
								
								
								<input type="hidden" name="return" value="<?php echo trim($url, '/').$this->url('checkout'); ?>" />
								<input type="hidden" name="cancel_return" value="<?php echo trim($url, '/').$this->url('checkout'); ?>" />
								<input type="hidden" name="notify_url" value="<?php echo trim($url, '/').$this->url('checkout_success'); ?>" />
								<input type='hidden' name="rm" value="2" />
								<input type="hidden" name="custom" value="<?php echo trim($cartId, ','); ?>" /> 
								
								<button type="submit" class="pay_now">
									<img src="<?php echo $url.$this->basePath('assets/design/frontend/default/images/pay_btn.png'); ?>" border="0" alt="Pay Now" />
								</button>
								
							</form>
						</td>
						<td width="15%" align="center">&nbsp;</td>
					</tr>  
				</table>
			</div>
		</div>
	</div>
</div>
