<?php //echo '<pre />'; print_r($this->upload); exit; ?>
<?php if ($this->group): ?>
<div class="row">
	<label class="form-label span5" for="option_id">
		<?php echo isset($this->group[0]['name']) ? $this->group[0]['name'] : ''; ?> *:
	</label>
	<div class="role">
	    <select name="option_id" id="option_id" class="inputArea inputbox required" onchange="loadGroup(this.value, 'a')">
	    	<option value=""> -- Select Option -- </option>
	        <?php foreach($this->group as $option): ?>
	        	<?php if ($this->upload['group_id'].'_'.$this->upload['group_option_index'] == $option['id'].'_'.$option['option_index']): ?>
	        	<option value="<?php echo $option['id'].'_'.$option['option_index']; ?>" selected="selected">
					<?php echo $option['option_name']; ?>
				</option>
	        	<?php else: ?>
	        	<option value="<?php echo $option['id'].'_'.$option['option_index']; ?>">
					<?php echo $option['option_name']; ?>
				</option>
				<?php endif; ?>
	        <?php endforeach; ?>
		</select>
	</div>
</div>
<?php endif; ?>

<div id="attribute_region">
<?php foreach($this->option as $key => $option): ?>
<?php $subitem = array(); ?>
<div class="row">
	<label class="form-label span5" for="attribute_<?php echo $key; ?>">
		<?php echo isset($option[0]['name']) ? $option[0]['name'] : ''; ?>:
	</label>
	<div class="role">
		<?php if ($option[0]['input_type'] == 2): ?>
			<input name="txtattribute[<?php echo $key; ?>]" id="attribute_<?php echo $key; ?>" class="inputArea inputbox" value="<?php echo isset($this->uploadAttr['attribute_'.$key]) ? $this->uploadAttr['attribute_'.$key] : ''; ?>" />
		<?php else: ?>
		    <select name="attribute[]" id="attribute_<?php echo $key; ?>" class="inputArea inputbox" onchange="showSubItem(this.value, <?php echo $key; ?>)">
		    	<option value=""> -- Select Option -- </option>
		    	<?php foreach($option as $item): ?>
		    		<?php $subitemSelected = ''; ?>
		    		<?php if ($item['subitem']): ?>
		    			<?php $subitem[$item['option_index']] = $item['subitem']; ?>
		    		<?php endif; ?>
		    		
		    		<?php if (array_key_exists($item['id'].'_'.$item['option_index'], $this->uploadAttr)): ?>
		    			<?php $subitemSelected = $this->uploadAttr[$item['id'].'_'.$item['option_index']]; ?>
		    		<option value="<?php echo $item['id'].'_'.$item['option_index']; ?>" selected="selected">
		        		<?php echo $item['option_name']; ?>
					</option>
		    		<?php else: ?>
		        	<option value="<?php echo $item['id'].'_'.$item['option_index']; ?>">
		        		<?php echo $item['option_name']; ?>
					</option>
					<?php endif; ?>
		        <?php endforeach; ?>
			</select>
			
			<?php if ($subitem): ?>
				<?php foreach($subitem as $key1 => $item): ?>
					<?php $itemList = explode(',', $item); ?>
					<select name="subitem[<?php echo $key; ?>][<?php echo $key1; ?>]" id="subitem_<?php echo $key.'_'.$key1; ?>" class="inputArea inputbox subitem_<?php echo $key; ?>" style="display:none">
						<?php foreach($itemList as $item): ?>
							<?php if ($subitemSelected == $item): ?>
							<option value="<?php echo $item; ?>" selected="selected">
				        		<?php echo $item; ?>
							</option>
							<?php else: ?>
				    		<option value="<?php echo $item; ?>">
				        		<?php echo $item; ?>
							</option>
							<?php endif; ?>
						<?php endforeach; ?>
					</select>
				<?php endforeach; ?>
			<?php endif; ?>
		<?php endif; ?>
	</div>
</div>
<?php endforeach; ?>

<div class="row">
	<label class="form-label span5" for="item_year">Year *:</label>
	<div class="role">
	    <input type="text" name="item_year" id="item_year" class="inputArea inputbox" value="<?php echo $this->upload['year']; ?>" />
	</div>
</div>

<div class="row">
	<label class="form-label span5" for="price_option">Price *:</label>
	<div class="role">
	    <select name="price_option" class="inputArea inputbox" id="price_option">
	    	<option value="negotiation" <?php echo $this->upload['price_option'] == 'negotiation' ? ' selected="selected"' : ''; ?>>Negotiation</option>
	    	<option value="fixed" <?php echo $this->upload['price_option'] == 'fixed' ? ' selected="selected"' : ''; ?>>Fixed</option>
	    </select>
	</div>
</div>

<div class="row">
	<label class="form-label span5" for="currency">Choose Currency *:</label>
	<div class="role">
	    <select name="currency" id="currency" class="inputArea inputbox">
	    	<option value="euro" <?php echo $this->upload['currency'] == 'euro' ? ' selected="selected"' : ''; ?>>EURO</option>
	    	<option value="dollar" <?php echo $this->upload['currency'] == 'dollar' ? ' selected="selected"' : ''; ?>>DOLLAR</option>
	    	<option value="fr" <?php echo $this->upload['currency'] == 'fr' ? ' selected="selected"' : ''; ?>>FR</option>
	    </select>
	</div>
</div>

<div class="row">
	<label class="form-label span5" for="recommanded_price">Recommanded Price for Guest User *:</label>
	<div class="role">
	    <input type="text" name="recommanded_price" id="recommanded_price" class="inputArea inputbox" value="<?php echo intval($this->upload['recommanded_price']); ?>" />
	</div>
</div>

<div class="row">
	<label class="form-label span5" for="dealer_price">Dealer Price *:</label>
	<div class="role">
	    <input type="text" name="dealer_price" id="dealer_price" class="inputArea inputbox" value="<?php echo intval($this->upload['dealer_price']); ?>" />
	</div>
</div>

<div class="row">
	<label class="form-label span5" for="dealer_price">Description *:</label>
	<div class="role">
	    <textarea name="description" id="description" class="inputArea inputbox" cols="10" rows="4"><?php echo $this->upload['description']; ?></textarea>
	</div>
</div>

<div class="details dealer_upload">
	<?php 
		$currency = '';
		if ($this->upload['currency'] == 'euro') { 
			$currency = '&euro; '.$this->upload['cart_price']; 
		} elseif ($this->upload['currency'] == 'dollar') { 
			$currency = '$ '.$this->upload['cart_price']; 
		}  elseif ($this->upload['currency'] == 'fr') { 
			$currency = 'fr. '.$this->upload['cart_price']; 
		}
	?>
	<div class="calculate_cost" style="display:none">Cost for this upload:<span><?php echo $currency; ?></span></div>
	<button type="submit" class="btn_lightblue upload_btn"><span>UPLOAD</span></button>
</div>
<script type="text/javascript">
//<!--
    $(document).ready(function() {
    	
    	$.validator.addMethod("lessThan", function(value, element, params) {
			return isNaN(value) && isNaN($(params).val()) 
			        || (Number(value) < Number($(params).val())); 
		}, 'Must be less than recommanded price.');

    	$("#dealer_upload").validate({
	        rules: {
	            category_id: "required",
	            option_id: 'required',
	            price_option:'required',
	            currency:'required',
	            //description:'required',
	            item_year: {
                   required: true,
                   digits:true,
                   minlength: 4,
                   maxlength: 4 
                },
                recommanded_price: {
                	required: true,
					digits:true
				},
				dealer_price: {
					digits:true,
					lessThan: "#recommanded_price"
				}
	        },
	        messages: {
	            category_id: {
					required: "This is required.",
				},
	            option_id: {
					required: "This is required.",
				},
	            item_year: {
					required: "This is required.",
				}
	        }
	    });
	    
    	$('.upload_btn').bind('touchstart click', function(){
            $("#dealer_upload").valid(); 
       });
    });
</script>
</div>