<?php $url = $this->getSettings('website_url'); ?>
<?php $noImage = $url.$this->basePath('assets/design/frontend/default/images/no-image.png'); ?>
<script type="text/javascript" src="<?php echo $url.$this->basePath('assets/design/frontend/default/js/jquery.rateit.min.js'); ?>"></script>
<link rel="stylesheet" media="screen" href="<?php echo $url.$this->basePath('assets/design/frontend/default/css/rateit.css'); ?>" />		
<div class="gallery">

	<?php echo $this->render('include/navigation.phtml'); ?>

	<div class="fright gallery_middle">
		
		<?php echo $this->render('include/add.phtml'); ?>
		
		<div class="list_of_gallery fleft">
			
			<div class="page_title">
				<h3><?php echo $this->title; ?></h3>
			</div>
			
			<div class="search_categories" style="text-align:left">
				<form method="get" action="">
					<span>Sorted By:</span>
					<?php $sortKey = isset($_GET['sort']) ? intval($_GET['sort']) : ''; ?>
					<select name="sort" onchange="this.form.submit()">
						<option value="1" <?php echo $sortKey == 1 ? 'selected' : ''; ?>>price high</option>
						<option value="2" <?php echo $sortKey == 2 ? 'selected' : ''; ?>>price low</option>
						<option value="3" <?php echo $sortKey == 3 ? 'selected' : ''; ?>>lastest</option>
						<option value="4" <?php echo $sortKey == 4 ? 'selected' : ''; ?>>oldest</option>
						<option value="5" <?php echo $sortKey == 5 ? 'selected' : ''; ?>>running out</option>
					</select>
				</form>
			</div>
			
			<div class="grid_panel my_uploads">
				<?php if (count($this->paginator)): ?>
				<ul class="itme_grid">
					<?php $i = 1; foreach ($this->paginator as $item): ?>
					<li class="list__item <?php echo $i==2 ? '': ($i == 1 ? 'first': 'last'); ?>">
						<div class="product_name">
							<a href="<?php echo $this->url('details', array('id' => $item['id'])) ?>" title="Click on for view details">
								<h3><?php echo substr($item['name'], 0, 42).(strlen($item['name']) > 42 ? '...' : ''); ?></h3>
							</a>
						</div>
						<?php 
						$image = '';
						if ($item['image']) { 
							$image = $item['image']; 
						}
						?>
						<div class="product_image">
							<a href="<?php echo $this->url('details', array('id' => $item['id'])) ?>" title="Click on for view details">
								<img src="<?php echo $image != '' ? $url.$this->basePath('media/product/'.$image) : $noImage; ?>" />
							</a>
						</div>
						<?php 
						$currency = '';
						if ($item['currency'] == 'euro') { 
							$currency = '&euro; '; 
						} elseif ($item['currency'] == 'dollar') { 
							$currency = '$ '; 
						}  elseif ($item['currency'] == 'fr') { 
							$currency = 'fr. '; 
						}
						if ($i == 3)
							$i = 1;
						else
							$i++;
						?>
						<div class="product_price">
							<?php echo $currency; ?> 
							<?php echo number_format($item['recommanded_price'], 2); ?>
						</div>
						
						<div class="product_expire_time">
							<div class="review_summary">
              					<?php echo $item['total_comment'] == 1 ? '( 1 ) comment': '( '.intval($item['total_comment']) .' ) comments'; ?>
								<div class="rating_box">
	              					<div class="rateit" data-rateit-value="<?php echo intval($item['rating']); ?>" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
	              				</div>
							</div>
						</div>
					</li>
					<?php endforeach; ?>
				</ul>
				<div class="pagination">
				<?php echo $this->paginationControl(
                                    $this->paginator,
                                    'Sliding',
                                    'include/pagination_control.phtml',
                                    array('route' => 'my_uploads', 'action' => 'myUploads')
                            ); 
                    ?>
                </div>
				<?php else: ?>
	                <div>
	                    <p>--No data found--</p>
	                </div>
				<?php endif; ?>
			</div>
			
		</div>
	</div>
</div>
