<?php $url = $this->getSettings('website_url'); ?>

		
<div class="gallery">

	<?php echo $this->render('include/navigation.phtml'); ?>

	<div class="fright gallery_middle">
		
		<?php echo $this->render('include/add.phtml'); ?>
		
		<div class="list_of_gallery fleft">
			
			<div class="search_categories" style="text-align:left">
				<form method="post" action="">
					<span>Sorted By:</span>
					<select name="filter" onchange="this.form.submit()">
						<option value="1">price high</option>
						<option value="2">price low</option>
						<option value="3">lastest</option>
						<option value="4">oldest</option>
						<option value="5">running out</option>
					</select>
				</form>
			</div>
			
			<div class="grid_panel">
				<ul class="itme_grid">
					<li class="list__item first">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item last">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item first">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item last">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item first">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item last">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item first">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
					<li class="list__item last">
						<h3>Image Title</h3>
						<img src="http://osvaldas.info/examples/responsive-equal-height-blocks/img/b9.jpg" />
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					</li>
				</ul>
			</div>
			
		</div>
	</div>
</div>
