<?php $url = $this->getSettings('website_url'); ?>
<div class="gallery">

	<?php echo $this->render('include/navigation.phtml'); ?>

	<div class="fright gallery_middle">
		
		<?php echo $this->render('include/add.phtml'); ?>
		
		<div class="list_of_gallery fleft">
			<div class="page_title">
				<h3>Do you wadt to upload another item / or pay and Check out?</h3>
			</div>
			
			<div class="user_activate" style="background:#fff;margin:0px;padding:0px;text-align:center;width:100%">
				<div>
					<p><a href="<?php echo $this->url('upload'); ?>" class="activate_link" style="white-space:nowrap;color:#000">UPLOAD NEW ITEM</a></p>
					<p><a href="<?php echo $this->url('checkout'); ?>" class="activate_link" style="white-space:nowrap;color:#000">&nbsp;&nbsp;PAY &amp; CHECKOUT&nbsp;&nbsp;</a></p>
				</div>
			</div>
			
		</div>
	</div>
</div>
