 <footer>
	<div class="disclaimer">
		<ul class="fright">
			<li><a href="<?php echo $this->basePath(''); ?>">Home</a></li>
			<li><a href="<?php echo $this->url('noRoute', array('identifier' => 'how-it-works')); ?>">How It Works</a></li>
			<li><a href="<?php echo $this->url('contact_us'); ?>">Contact Us</a></li>
		</ul>
		<div class="copyright">
			<?php //echo $this->getSettings('copyright'); ?>
		</div>
	</div>
</footer>