<div class="navigation fleft">
	<ul>
		<li style="background-color:transparent;">
			<a href="<?php echo $this->url('search'); ?>">SEARCH</a>
		</li>
		<li>
			<a href="#">UPLOAD</a>
		</li>
		<li>
			<a href="#">STATUS</a>
		</li>
		<li>
			<a href="#">ITEM SETTINGS</a>
		</li>
		<li>
			<a href="#">RATING</a>
		</li>
		<li>
			<a href="<?php echo $this->url('account'); ?>">MY ACCOUNT</a>
		</li>
	</ul>
</div>