<script type="text/javascript">
    //<!--
    var userid = [];
    
    $(document).ready(function() {
       $('.categoryid_checkbox').click(function() {
            if (this.checked) {
                 userid.push(this.value);
            } else {
                var index = userid.indexOf(this.value); 
                if (index != -1)
                    userid.splice(index,1);
            }
            $('input[name=categoryids]').val(userid);
       }); 
    });
    
    function showStatus(value) {
        if (value == 'status')
            $('#status').css('display', 'inline-block');
        else
            $('#status').hide();
    }
    
    function checkCategoryIds() {
        if ($('input[name=categoryids]').val() != '') {
            return true;
        }
        alert('Please select category');
        return false;
    }
    
    function toggleChecked(status) {
        $(".categoryid_checkbox").each( function() {
            $(this).attr("checked",status);
            if(status){
              $(this).parent().addClass('checked');  
              userid.push(this.value);
            } else {
              $(this).parent().removeClass('checked');
              var index = userid.indexOf(this.value); 
                if (index != -1)
                    userid.splice(index,1);
            }
        })
        $('input[name=categoryids]').val(userid);
        //onclick="toggleChecked(this.checked)"
    }    
    //-->
</script>

<style type="text/css">
#uniform-status {
    display: none;
}
</style>

<div class="row-fluid">

    <div class="span10">
    
        <div class="heading">

            <h3>Category List</h3>                    

        </div><!-- End .heading-->

    </div>

</div>

<div class="row-fluid">

    <div class="span10 tableBox">
        
        <div class="row-fluid">
                 
            <div class="box gradient admin">

                <div class="title">
                    <div class="selectbox">   
                        <form method="post" action="<?php echo $this->url('product', array('action' => 'mass-category-modification')); ?>">
                            <select name="action" onchange="showStatus(this.value)">
                                <option selected="selected">Choose action</option>
                                <option value="delete">Delete</option>
                                <option value="status">Change Status</option>
                            </select>
                            <select name="status" id="status" style="display:none">
                                <option selected="selected">Change Status</option>
                                <option value="1">Active</option>
                                <option value="0">In Active</option>
                            </select>
                            <input type="hidden" name="categoryids" />
                            <button type="submit" onclick="return checkCategoryIds();" class="btn btn-inverse">Submit</button>
                           
                        	<a href="<?php echo $this->url('product', array('action' => 'new-category')); ?>" class="btn btn-success">Add Category</a>
                        </form>
                        
                    </div>
                    
                            
                </div>
                <div class="content noPad clearfix">
                    <div class="scrollable">
                       <table cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                         <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" name="optionsCheckboxList1" value="option1" class="styled" onclick="toggleChecked(this.checked)" />
                                </th>
                                <th>Name</th>
                                <th>Status</th>
                                <th>Include Navigation</th>
                                <th>Created Date</th>
                                <th>Updated Date</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php 
                            if (count($this->paginator)): 
                                $iterator = 1;
                                foreach ($this->paginator as $item): 
                        ?>
                            <tr class="<?php if ($iterator++%2 == 0) echo 'even'; else echo 'odd'; ?>">
                                <td>
                                    <input type="checkbox" class="categoryid_checkbox" name="categoryid[]" value="<?php echo $item['category_id']; ?>" class="styled" />
                                </td>
                                <td class="sorting2">
                                    <?php if ($item['image']): ?>
                                        <img width="35" height="35" class="image" alt="" src="<?php echo $this->basePath('media/category/35x35/'.$item['image']); ?>" />
                                    <?php else: ?>
                                        <img class="image" alt="" src="<?php echo $this->basePath('assets/design/admin/images/avatar.png'); ?>" />
                                    <?php endif; ?>
                                    <label><?php echo $item['category_name']; ?></label>
                                </td>
                                <td><?php echo $item['is_active'] == 1? 'Active':'In Active'; ?></td>
                                <td><?php echo $item['include_navigation'] == 1? 'Yes':'No'; ?></td>
                                <td><?php echo date('d/m/Y', strtotime($item['created_date'])); ?></td>
                                <td><?php echo date('d/m/Y', strtotime($item['updated_date'])); ?></td>
                                <td>
                                    
                                <a href="<?php echo $this->url('product', array('action' => 'edit-category', 'id' => $item['category_id'])); ?>" class="btn btn-success">Edit Category</a>
                          
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="6">--No data found--</td>
                            </tr>
                        <?php endif; ?>
                    
                        </tbody>
                    </table>
                    
                    <?php echo $this->paginationControl(
                                                        $this->paginator,
                                                        'Sliding',
                                                        'include/pagination_control.phtml',
                                                        array('route' => 'product', 'action' => 'category')
                            ); 
                    ?>
                    
                    </div>
                </div>

            </div><!-- End .box -->                           
            
        </div>
        
    </div>
    
</div>  