<script type="text/javascript">
    //<!--
    var userid = [];
    
    $(document).ready(function() {
       $('.productid_checkbox').click(function() {
            if (this.checked) {
                 userid.push(this.value);
            } else {
                var index = userid.indexOf(this.value); 
                if (index != -1)
                    userid.splice(index,1);
            }
            $('input[name=productids]').val(userid);
       }); 
    });
    
    function showStatus(value) {
        if (value == 'status')
            $('#status').css('display', 'inline-block');
        else
            $('#status').hide();
    }
    
    function checkProductIds() {
        if ($('input[name=productids]').val() != '') {
            return true;
        }
        alert('Please select product');
        return false;
    }
    
    function toggleChecked(status) {
        $(".productid_checkbox").each( function() {
            $(this).attr("checked",status);
            if(status){
              $(this).parent().addClass('checked');  
              userid.push(this.value);
            } else {
              $(this).parent().removeClass('checked');
              var index = userid.indexOf(this.value); 
                if (index != -1)
                    userid.splice(index,1);
            }
        })
        $('input[name=productids]').val(userid);
        //onclick="toggleChecked(this.checked)"
    }
    
    //-->
</script>

<style type="text/css">
#uniform-status {
    display: none;
}
</style>

<div class="row-fluid">

    <div class="span10">
    
        <div class="heading">

            <h3>Product List</h3>                    

        </div><!-- End .heading-->

    </div>

</div>

<div class="row-fluid">

    <div class="span10 tableBox">
        
        <div class="row-fluid">
                 
            <div class="box gradient admin">

                <div class="title">
                    <div class="selectbox">   
                            <form method="post" action="<?php echo $this->url('product', array('action' => 'mass-product-modification')); ?>">
                                <select name="action" onchange="showStatus(this.value)">
                                    <option selected="selected">Choose action</option>
                                    <option value="delete">Delete</option>
                                    <option value="status">Change Status</option>
	                            </select>
	                            
	                            <select name="status" id="status" style="display:none">
	                                <option selected="selected">Change Status</option>
	                                <option value="1">Active</option>
	                                <option value="2">In Active</option>
	                            </select>
	                            
                                <input type="hidden" name="productids" />
                                <button type="submit" onclick="return checkProductIds();" class="btn btn-inverse">Submit</button>
                                    <a href="<?php echo $this->url('product', array('action' => 'new-product')); ?>" class="btn btn-success">Add Product</a>
                            </form>
                    </div>
                    
                            
                </div>
                <div class="content noPad clearfix">
                    <div class="scrollable">
                       <table cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                         <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" name="optionsCheckboxList1" value="option1" class="styled" onclick="toggleChecked(this.checked)" />
                                </th>
                                <th>Name</th>
                                <th>Model</th>
                                <th>Brand</th>
                                <th>Status</th>
                                <th>Created Date</th>
                                <th>Updated Date</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php 
                            if (count($this->paginator)): 
                                $iterator = 1;
                                foreach ($this->paginator as $item): 
                        ?>
                            <tr class="<?php if ($iterator++%2 == 0) echo 'even'; else echo 'odd'; ?>">
                                <td>
                                    <input type="checkbox" class="productid_checkbox" name="productid[]" value="<?php echo $item['id']; ?>" class="styled" />
                                </td>
                                <td class="sorting2">
                                    <?php if ($item['image']): ?>
                                        <img width="35" height="35" class="image" alt="" src="<?php echo $this->basePath('media/product/35x35/'.$item['image']); ?>" />
                                    <?php else: ?>
                                        <img class="image" alt="" src="<?php echo $this->basePath('assets/design/admin/images/avatar.png'); ?>" />
                                    <?php endif; ?>
                                    <label><?php echo $item['name']; ?></label>
                                </td>
                                
                                <td><?php echo $item['model_name']; ?></td>
                                <td><?php echo $item['brand_name']; ?></td>
                                <td><?php echo $item['status'] == 1 ? 'Active' : 'In Active'; ?></td>
                                <td><?php echo date('d/m/Y', strtotime($item['created_date'])); ?></td>
                                <td><?php echo date('d/m/Y', strtotime($item['updated_date'])); ?></td>
                                <td>
                                    <a href="<?php echo $this->url('product', array('action' => 'edit-product', 'id' => $item['id'])); ?>" class="btn btn-success">Edit Product</a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="7">--No data found--</td>
                            </tr>
                        <?php endif; ?>
                    
                        </tbody>
                    </table>
                    
                    <?php echo $this->paginationControl(
                                                        $this->paginator,
                                                        'Sliding',
                                                        'include/pagination_control.phtml',
                                                        array('route' => 'product_list')
                            ); 
                    ?>
                    
                    </div>
                </div>

            </div><!-- End .box -->                           
            
        </div>
        
    </div>
    
</div>  