
<style type="text/css">
#vtab {
    margin: auto;
    display:block;
    clear:both;
    overflow: hidden;
}
#vtab > ul > li {
    border-bottom: 1px solid #232324;
    border-top: 1px solid #E5E8E9;
    color: #FFFFFF;
    font-size: 13px;
    padding:10px;
    font-family: 'varela_roundregular';
    text-shadow: 0 1px 1px #111112;
    background-color: #353535;
    cursor:pointer;
}

#vtab > ul > li.selected {
    opacity: 1;
    border: 1px solid #ddd;
    border-right: none;
    background-color: #E5E8E9;
    color:#232324;
}
#vtab > ul {
    float: left;
    width: 168px;
    text-align: left;
    display: block;
    margin: auto 0;
    padding: 0;
}
#vtab > div {
    background-color: #fafafa;
    margin-left: 166px;
    border: 1px solid #ddd;
    padding: 12px;
    display:none;
}
#vtab > div > h4 {
    color: #800;
    font-size: 1.2em;
    border-bottom: 1px dotted #800;
    padding-top: 5px;
    margin-top: 0;
}

#vtab > ul > li.selected{
    border-right: 1px solid #fff !important;
}
#vtab > ul > li {
    border-right: 1px solid #ddd !important;
}
#vtab > div {
    z-index: -1 !important;
    left:1px;
}

</style>
<script type="text/javascript" src="<?php echo $this->basePath('assets/ckeditor/ckeditor.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/ckfinder.js'); ?>"></script>
	
<script src="<?php echo $this->basePath('assets/js/bootstrap-datetimepicker.min.js'); ?>"></script>
<link href="<?php echo $this->basePath('assets/design/admin/admin/css/bootstrap-datetimepicker.min.css'); ?>" rel="stylesheet" type="text/css" />
<script type="text/javascript">
    //<!--
    $(document).ready(function() {
        
        var $items = $('#vtab>ul>li');
        
       $("#product").validate({
            rules: {
                name: {
                   required: true,
                   maxlength: 255
                },
                actual_price: {
                    required:true,
                    number:true
                },
                description: {
                   required: true
                },
                status: {
                    required: true,
                    digits:true
                },
                start_date: {
                   required: true
                },
            },
            messages: {
                name: {
                    required: "Fill me please",
                    maxlength: "First name is bigger"
                },
                actual_price: {
                    required: "Fill me please",
                    number: "Please enter only number"
                },
                description: {
                    required: "Fill me please"
                },
                status: {
                    required: "Fill me please",
                    digits: "Please enter digits"
                },
                start_date: {
                    required: ""
                },
            }   
        });
   
        
        
        $items.click(function() {
            $items.removeClass('selected');
            $(this).addClass('selected');
        
            //var index = $items.index($(this));
            //$('#vtab>div').hide().eq(index).show();
            $('#vtab>div').hide();
            $('#vtab>div#'+this.id+'_content').show()
        });

       
    })
    
    function deleteRow(tableId, row)
    {
        var i = row.parentNode.parentNode.rowIndex;
        document.getElementById(tableId).deleteRow(i);
    }
    
    var xhr = null;
        
    function deleteGalleryRow(tableId, gid,pid, row)
    {
        if( xhr != null ) {
		  xhr.abort();
		  xhr = null;
        }
	                  
        <?php if($this->type == 'Auction' || (isset($this->editProductInfo[0]['is_auction'])&& $this->editProductInfo[0]['is_auction']==1)){ 
            $url = $this->url('product', array('action' => 'delete-gallery')).'?is_auction=1';
        } else {
            $url = $this->url('product', array('action' => 'delete-gallery'));
        } ?>
    
    	xhr = jQuery.ajax({
    		type: "POST"
    		, url: "<?php echo $url; ?>"
    		, data: 'gid='+gid+'&pid='+pid+'&isAjax=1'
    		, dataType: 'json'
    		, success: function(response)
            {
    	
                 
                if(response.error==0 ) {
                    var i = row.parentNode.parentNode.rowIndex;
                    document.getElementById(tableId).deleteRow(i);      
                    jQuery("#messageAjaxBox").html(response.msg).css('color', 'red').show();         
                } else {
                    if(response.msg=='session_expired') {
                        window.location="<?php echo $this->url('admin_login'); ?>";
                        return false;
                    } else{
                        jQuery("#messageAjaxBox").html(response.msg).css('color', 'red').show();
                        return false;
                    }
                } 
    		}
    	});
    }
    
    
    function insRow(tableId)
    {
        var totalRow = document.getElementById(tableId).rows.length;
        var x=document.getElementById(tableId).insertRow(totalRow);
        
        var c1=x.insertCell(0);
        var c2=x.insertCell(1);
        var c3=x.insertCell(2);
               
        c1.innerHTML = '<input type="text" name="custom_options_label[]" class="span7 text" />';
        c2.innerHTML = '<input type="text" name="custom_options_value[]" class="span7 text" />';
        c3.innerHTML = '<a href="javascript:void(0)" onclick="deleteRow(\''+tableId+'\', this)">Remove</a>' ;

    }
    
    function insGalleryRow(tableId) {
        
        var totalRow = document.getElementById(tableId).rows.length;
        var x=document.getElementById(tableId).insertRow(totalRow);
        
        var c1=x.insertCell(0);
        var c2=x.insertCell(1);
        var c3=x.insertCell(2);
        
        var lastindex = parseInt(document.getElementById('lastindex_gallery').value);
        
        c1.innerHTML = '<input type="file" name="gallery['+lastindex+']" class="span7 text" />';
        if (totalRow == 1)
            c2.innerHTML = '<input type="radio" value="'+lastindex+'" checked="checked" id="gallery" name="gallery" class="span7 text" />';
        else
            c2.innerHTML = '<input type="radio" value="'+lastindex+'" id="gallery" name="gallery" class="span7 text" />';
            
        c3.innerHTML = '<a href="javascript:void(0)" onclick="deleteRow(\''+tableId+'\', this)">Remove</a>' ;
        
        lastindex = lastindex+1;
        document.getElementById('lastindex_gallery').value = lastindex;
    }
        
    
    //-->

</script>

<div class="row-fluid">

    <div class="span10">
    
        <div class="heading">
            <?php if ($this->editProductInfo): ?>
                <h3>Edit <?php echo $this->type; ?> </h3>
            <?php else: ?>
                <h3>Add New <?php echo $this->type; ?></h3>
            <?php endif; ?>
        </div><!-- End .heading-->
        
        <div id="messageAjaxBox" style="padding: 10px; color:red;display:none;"></div>
        
        <div class="backlink">
            <?php if ($this->type == 'Auction'): ?>
                <a href="<?php echo $this->url('auction_list'); ?>">Back to Auction List</a>
            <?php else: ?>
                <a href="<?php echo $this->url('product', array('action' => 'product-list')); ?>">Back to Product List</a>
            <?php endif; ?>
        </div>


    </div>

</div>
               
<div class="row-fluid">

    <div class="span10 tableBox">
        
        <div class="row-fluid">
                 
            <div class="span12">
            
                <div class="usertitle">
                    Product details
                </div>
                
                <!-- Tab-->
                <form class="form-horizontal" id="product" method="post" action="<?php echo $this->url('product', array('action' => 'new-product', 'id' => $this->productid)); ?><?php if ($this->type == 'Auction') echo '?is_auction=1'; ?>" enctype="multipart/form-data">
                     <div id="vtab">
                        
                        <!-- Left Side Tab Menu -->
                        
                        <ul>
                            <li id="tab_general" class="selected">General</li>
                            <li id="tab_custom_options">Custom Options</li>
                            <li id="tab_category">Category</li>
                            <li id="tab_gallery">Gallery</li>
                        </ul>
                        
                        <!-- EndLeft Side Tab Menu -->
                        
                        <!-- Right Side Tab Menu Content -->
                        
                        <!-- General -->
                        <div id="tab_general_content" style="display: block;">
                            <div class="rowfluidWrap">
                                <div class="row-fluid">                                                                        
                                    <div class="form-row row-fluid">
                                        <div class="span12">
                                            <div class="row-fluid">
                                                <label class="form-label span5" for="name" style="text-align: left;">Name:*</em></label>
                                                <input class="span7" id="name" name="name" class="required" type="text" value="<?php echo isset($this->editProductInfo[0]['name']) ? $this->editProductInfo[0]['name']:''; ?>" />
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                    <?php if(isset($this->editProductInfo[0]['is_auction'])&& $this->editProductInfo[0]['is_auction']==1){ ?>
                                    <div class="form-row row-fluid">
                                        <div class="span12">
                                            <div class="row-fluid">
                                                <label class="form-label span5" for="actual_price" style="text-align: left;">Price:*</em></label>
                                                <strong><?php echo isset($this->editProductInfo[0]['actual_price']) ? $this->editProductInfo[0]['actual_price']:''; ?></strong>
                                            </div>
                                        </div>
                                    </div>
                                    <?php } else { ?>                                                                        
                                    <div class="form-row row-fluid">
                                        <div class="span12">
                                            <div class="row-fluid">
                                                <label class="form-label span5" for="actual_price" style="text-align: left;">Price:*</em></label>
                                                <input class="span7" id="actual_price" name="actual_price" class="required number" type="text" value="<?php echo isset($this->editProductInfo[0]['actual_price']) ? $this->editProductInfo[0]['actual_price']:''; ?>" />
                                            </div>
                                        </div>
                                    </div>
                                    <?php } ?>
                                    
                                    <?php if($this->type == 'Auction' || (isset($this->editProductInfo[0]['is_auction'])&& $this->editProductInfo[0]['is_auction']==1)){ ?>
                                    <div class="form-row row-fluid">
                                        <div class="span12">
                                            <div class="row-fluid">
                                                <label class="span5" for="status">Auction Status:*</label>
                                                <div class="role">
                                                    <?php if(isset($this->editProductInfo[0]['status'])) { ?>
                                                        <?php if(isset($this->editProductInfo[0]['status'])&& ($this->editProductInfo[0]['status']==4 || $this->editProductInfo[0]['status']==5)){ ?>
                                                            <?php echo (isset($this->editProductInfo[0]['status'])&& $this->editProductInfo[0]['status']==4) ? 'Sold' : ''; ?>
                                                            <?php echo (isset($this->editProductInfo[0]['status'])&& $this->editProductInfo[0]['status']==5) ? 'Win and Sold' : ''; ?>
                                                            <input class="span7" name="status" type="hidden" value="<?php echo $this->editProductInfo[0]['status']; ?>" />
                                                        <?php } else { ?>
                                                        <select name="status" id="status" class="required digits">
                                                            <option value="1" <?php echo (isset($this->editProductInfo[0]['status'])&& $this->editProductInfo[0]['status']==1) ? 'selected':''; ?>>Active</option>
                                                            <option value="2" <?php echo (isset($this->editProductInfo[0]['status'])&& $this->editProductInfo[0]['status']==2) ? 'selected':''; ?>>In Active</option>
                                                            <option value="3" <?php echo (isset($this->editProductInfo[0]['status'])&& $this->editProductInfo[0]['status']==3) ? 'selected':''; ?>>Auction Close</option>
                                                        </select>
                                                        <?php } ?>
                                                    <?php } else { ?>
                                                        <select name="status" id="status" class="required digits">
                                                            <option value="1">Active</option>
                                                            <option value="2">In Active</option>
                                                            <option value="3">Auction Close</option>
                                                        </select>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    <div class="form-row row-fluid">
                                        <div class="span12">
                                            <div class="row-fluid">

                                                    <div class="well">
                                                      <div id="datetimepicker1" class="input-append date">
                                                        <label class="form-label span5" for="start_date" style="text-align: left;width: 277px;">Start date:*</em></label>
                                                        <input data-format="yyyy-MM-dd hh:mm:ss" type="text" name="start_date" id="start_date" style="width: auto;" value="<?php echo isset($this->editProductInfo[0]['start_date']) ? $this->editProductInfo[0]['start_date']:''; ?>" />                                                        
                                                        <span class="add-on">
                                                          <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
                                                        </span>
                                                      </div>
                                                    </div>
                                                    <script type="text/javascript">
                                                      $(function() {
                                                        $('#datetimepicker1').datetimepicker();
                                                      });
                                                    </script>                                                
                                                    <style type="text/css">
                                                    #datetimepicker1 label.error {
                                                        display:none !important;
                                                    }
                                                    .bootstrap-datetimepicker-widget {
                                                        top: 529px;                                                                                 
                                                    }
                                                    .well {
                                                        padding: 0;
                                                        background: transparent;
                                                        border: 0;
                                                        box-shadow: 0 0 0 0;
                                                    }
                                                    </style>
                                                
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                    
                                    
                                    
                                    <?php } ?>
                                                                        
                                    <div class="form-row row-fluid">
                                        <div class="span12">
                                            <div class="row-fluid">
                                                <label class="form-label span5" for="description" style="text-align: left;margin:0;margin-bottom:10px;">Description:*</label>
                                                <br />
                                                <br />
                                                <textarea class="span7" id="description" class="required" name="description" ><?php echo isset($this->editProductInfo[0]['description']) ? $this->editProductInfo[0]['description']:''; ?></textarea>
                                            
                                                <script type="text/javascript">
                                    			//<![CDATA[
                                    				var editor = CKEDITOR.replace( 'description',
                                    					{
                                    						fullPage : false,
                                    						extraPlugins : 'docprops',
                                                            toolbar: [
                                                            	{ name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
                                                            	{ name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
                                                            	{ name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ] },
                                                            	{ name: 'tools', items: [ 'Maximize' ] },
                                                            	{ name: 'document', groups: [ 'mode', 'document', 'doctools' ], items: [ 'Source' ] },
                                                            	{ name: 'others', items: [ '-' ] },
                                                            	'/',
                                                            	{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
                                                            	{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ] },
                                                            	{ name: 'styles', items: [ 'Styles', 'Format' ] },
                                                            	{ name: 'about', items: [ 'About' ] }
                                                            ],
                                                            filebrowserBrowseUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/ckfinder.html'); ?>',
                                                         	filebrowserImageBrowseUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/ckfinder.html?type=Images'); ?>',
                                                         	filebrowserFlashBrowseUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/ckfinder.html?type=Flash'); ?>',
                                                         	filebrowserUploadUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files'); ?>',
                                                         	filebrowserImageUploadUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'); ?>',
                                                         	filebrowserFlashUploadUrl : '<?php echo $this->basePath('assets/ckeditor/plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'); ?>',
                                                         	filebrowserWindowWidth : '700',
                                                         	filebrowserWindowHeight : '700'
                                    					});
                                                    CKFinder.setupCKEditor( editor, '<?php echo $this->basePath('media'); ?>' ) ;
                                    
                                    			//]]>
                                    			</script>
            
                                            </div>
                                        </div>
                                    </div> 
                                
                                </div>
                            </div>
                        </div>
                        
                        <!-- Custom Options -->
                        <div id="tab_custom_options_content">
                            <div class="rowfluidWrap">
                                <div class="row-fluid">                                                                        
                                    
                                     <table width="100%" id="custom_options">
                                        <tr style="background-color: #E5E8E9; padding:4px;width:100%">
                                            <th>Label</th>
                                            <th>Value</th>
                                            <th>
                                                <button id="successR" type="button" class="btn marginR10 btn-success pull-right" onclick="insRow('custom_options')">
                                                    Add Option
                                                </button>
                                            </th>
                                        </tr>
                                        <?php if(isset($this->editProductInfo[0]['custom_options'])): ?>
                                            <?php $customOptions = unserialize($this->editProductInfo[0]['custom_options']); ?>
                                            <?php foreach($customOptions as $label => $value): ?>
                                                <tr>
                                                    <th><input type="text" value="<?php echo $label; ?>" name="custom_options_label[]" class="span7 text" /></th>
                                                    <th><input type="text" value="<?php echo $value; ?>" name="custom_options_value[]" class="span7 text" /></th>
                                                    <th><a href="javascript:void(0)" onclick="deleteRow('custom_options', this)">Remove</a></th>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                     </table>
                                     
                                </div>
                            </div>
                        </div>
                        
                        <!-- Category -->
                        <div id="tab_category_content">
                            <div class="rowfluidWrap">
                                <div class="row-fluid">                                                                        
                                    
                                     
                                    <div class="form-row row-fluid">
                                        <div class="span12">
                                            <div class="row-fluid">
                                                <div class="role">
                                                    <?php 
                                                    $productCategory = array();
                                                    $i = 1;
                                                    foreach ($this->productCategory as $value):
                                                        $productCategory[$value['category_id']] = $value['product_id'];
                                                    endforeach;
                                                    
                                                    foreach ($this->categories as $category): ?>
                                                        <input type="checkbox" value="<?php echo $category['category_id']; ?>" name="category_ids[]" <?php echo array_key_exists($category['category_id'], $productCategory) ? 'checked="checked"': ''; ?> />
                                                        <?php echo $category['category_name']; ?>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                
                                </div>
                            </div>
                        </div>
                        
                        <!-- Gallery -->
                        
                        <div id="tab_gallery_content">
                            <div class="rowfluidWrap">
                                <div class="row-fluid">                                                                        
                                    
                                     <table width="100%" id="gallery_grid">
                                        <tr style="background-color: #E5E8E9; padding:4px;width:100%">
                                            <th>Image</th>
                                            <th>Base Image</th>
                                            <th>
                                                <button id="successR" type="button" class="btn marginR10 btn-success pull-right" onclick="insGalleryRow('gallery_grid')">
                                                    Add Image
                                                </button>
                                             </th>
                                        </tr>
                                        
                                        <?php 
                                        $i = 1;
                                        foreach ($this->productGallery as $gallery): ?>
                                            <tr>
                                                <th>
                                                    <img width="50" height="50" class="image" alt="" src="<?php echo $this->basePath('media/'.strtolower($this->type).'/'.$gallery['product_id'].'/'.$gallery['image_name']); ?>" />
                                                </th>
                                                <th><input type="radio" value="<?php echo $gallery['gallery_id']; ?>" id="gallery" name="gallery" class="span7 text" <?php echo $gallery['is_baseimage']==1 ? 'checked="checked"': ''; ?> /></th>
                                                <th><a href="javascript:void(0)" onclick="deleteGalleryRow('gallery_grid','<?php echo $gallery['gallery_id']; ?>', '<?php echo $gallery['product_id']; ?>', this)">Remove</a></th>
                                            </tr>
                                        <?php endforeach; ?>
                                     </table>
                                     
                                     
                                     <input type="hidden" value="<?php echo $i; ?>" id="lastindex_gallery" />
                                </div>
                            </div>
                        </div>
                        
                        <!-- End Right Side Tab Menu Content -->
                    </div>
                     <!-- End Tab-->
                     
                     <div class="form-row row-fluid">
                        <div class="span12">
                            <div class="row-fluid">
                                <div class="form-actions">
                                    <div class="controls">
                                        <button class="btn btn-primary pull-right marginL10 btn-danger" style="margin-left:20px" type="button" onclick="window.location = '<?php echo $this->url('product', array('action' => 'product-list')); ?>';">Cancel</button>
                                        <button id="successR" type="submit" class="btn marginR10 btn-success pull-right">Save</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </form>
                
             </div>                         
        </div>
    </div>
</div>